$schema: "http://json-schema.org/draft-07/schema#"
$id: "tokenization.clm_training.schema.yaml"

description: "Main schema for tokenization whenever Causal Language Model training is performed"

allOf:
  - $ref: "tokenization.schema.yaml"
  - type: object
    properties:
      tokenizer:
        properties:
          task:
            type: string
            const: "clm_training"
          overlap:
            type: integer
            minimum: 0
            description: "Number of tokens to overlap between examples"
    
        required:
          - overlap

      

