# config/distributed/fsdp.schema.yaml
includes: ['../base.schema.yaml']
mapping:
  distributed:
    mapping:
      config:
        type: map
        required: yes
        mapping:
          sharding_strategy:
            type: str
            enum: ['FULL_SHARD', 'SHARD_GRAD_OP']
          cpu_offload:
            type: bool
