$schema: "http://json-schema.org/draft-07/schema#"
$id: "model.schema.yaml"
description: "Schema for model configuration"

type: object
properties:
  model_name:
    type: string
    description: "Name or path of the model to load"
  
  precision:
    type: string
    default: "bf16-true"
    description: "Precision for the loaded model"
    enum: ["bf16-true", "fp32", "fp16"]

  verbose_level:
    type: string
    enum: ["DEBUG", "INFO", "WARNING", "ERROR"]
    default: "INFO"
    description: "Logging verbosity level"
  
  log_every_n_steps:
    type: integer
    default: 10
    description: "Log training metrics every N steps"

required:
  - model_name
