$schema: "http://json-schema.org/draft-07/schema#"
$id: "base"
type: object
properties:
  task:
    type: string
    enum: ["tokenization", "pretraining"]
  experiment_name:
    type: string
    pattern: '^.+$'
required:
  - task
  - experiment_name
