$schema: "http://json-schema.org/draft-07/schema#"
$id: "base"
type: object
properties:
  task:
    type: string
    enum: ["tokenization", "clm_training", "mlm_training", "lm_evaluation", "lm_inference", "publish", "tokenization_instruction"]
  experiment_name:
    type: string
    pattern: '^.+$'
  verbose_level:
    type: integer
    minimum: 0
    maximum: 4
required:
  - task
  - experiment_name
