# config/base.schema.yaml
type: map
mapping:
  task:
    type: str
    required: yes
    enum: ['tokenization', 'pretraining']
  experiment_name: 
    type: str
    regex: \w+
  distributed:
    type: map
    mapping:
      strategy: 
        type: str
        enum: ['fsdp', 'ddp', 'none']
      config: 
        type: map
        nullable: yes
