$schema: "http://json-schema.org/draft-07/schema#"
$id: "tokenization.schema.yaml"
title: "Tokenization Task Schema"
allOf:
  - $ref: "base.schema.yaml"
properties:
  dataset_path:
    oneOf:
      - type: string
      - type: array
        items:
          type: string
  tokenizer_name:
    type: string
  batch_size:
    type: integer
    minimum: 1
  chunk_size:
    type: integer
    minimum: 64
required: [dataset_path, tokenizer_name]
