$schema: "http://json-schema.org/draft-07/schema#"
$id: "tokenization.schema.yaml"
allOf:
  - $ref: "base.schema.yaml"
  - type: object
    properties:
      tokenizer:
        type: object
        properties:
          name:
            type: string
            description: "HuggingFace tokenizer name"
          context_length:
            type: integer
            minimum: 1
            maximum: 100000
          overlap:
            type: integer
            minimum: 0
          task:
            type: string
            enum: ["causal_pretraining"]
            default: "causal_pretraining"
        required:
          - name
          - context_length
      
      dataset:
        type: object
        properties:
          source:
            type: string
            enum: ["huggingface", "local"]
          nameOrPath:
            type: string
            description: "Dataset name for HuggingFace or local path"
          format:
            type: string
            enum: ["dataset", "files"]
          file_config:
            type: object
            properties:
              format:
                type: string
                default: "any"
                enum: ["csv", "txt", "json", "any"]
              text_column:
                type: string
              encoding:
                type: string
                default: "utf-8"
          save_raw:
            type: object
            properties:
              enabled:
                type: boolean
              path:
                type: string
        required:
          - source
          - nameOrPath
          - format

      output:
        type: object
        properties:
          path:
            type: string
            description: "Path to save tokenized dataset"
        required:
          - path
          
    required:
      - tokenizer
      - dataset
      - output
