$schema: "http://json-schema.org/draft-07/schema#"
$id: "tokenization.mlm_training.schema.yaml"

description: "Main schema for tokenization whenever Masked Language Model training is performed"

allOf:
  - $ref: "tokenization.schema.yaml"
  - type: object
    properties:
      tokenizer:
        type: object
        properties:
          task:
            type: string
            const: "mlm_training"
          mlm_probability:
            type: number
            minimum: 0
            maximum: 1
            default: 0.15
            description: "Probability of selecting a token for masking"
          masking_strategy:
            type: object
            properties:
              mask_token_prob:
                type: number
                default: 0.8
                description: "Of selected tokens, probability of using [MASK]"
              random_token_prob: 
                type: number
                default: 0.1
                description: "Of selected tokens, probability of random replacement"
              unchanged_prob:
                type: number
                default: 0.1
                description: "Of selected tokens, probability of keeping unchanged"
          mask_token_id:
            type: integer
            default: 103
            description: "Token ID for [MASK] token"
          mask_special_tokens:
            type: boolean
            default: false
            description: "Whether to mask special tokens"
          exclude_token_ids:
            type: array
            items:
              type: integer
            default: []
            description: "List of token IDs to exclude from masking"

        required:
          - task
          - mlm_probability
          - masking_strategy
          - mask_token_id