task: publish
experiment_name: tutorial_publish
verbose_level: 4

# Publish configuration
publish:
  # Format conversion
  format: fsdp
  base_model: gpt2
  checkpoint_path: /path/to/your/checkpoint.pt
  
  # Upload configuration
  host: huggingface
  repo_id: your-username/your-model-name
  commit_message: Add gpt2 model trained with Continual Pretraining Framework
  
  # Advanced options
  max_shard_size: 5GB
  safe_serialization: true
  create_pr: false
