$schema: "http://json-schema.org/draft-07/schema#"
$id: "clm_training.schema.yaml"
description: "Schema for Causal Language Model training configuration"

allOf:
  - $ref: "../base.schema.yaml"
  - $ref: "components/model.schema.yaml"
  - $ref: "components/data.schema.yaml"
  - $ref: "components/training_args.schema.yaml"
  - $ref: "components/optimizer.schema.yaml"
  - $ref: "components/scheduler.schema.yaml"
  - type: object
    properties:
      # CLM-specific model default
      model_name:
        type: string
        default: "meta-llama/Meta-Llama-3-8B"
        description: "Name or path of the causal language model to load"

      # Training strategy arguments
      parallelization_strategy:
        type: string
        enum: ["none", "ddp", "fsdp", "deep_speed", "dp"]
        default: "none"
        description: "Which distributed training strategy to use"

      # Parallelization config - details differ depending on strategy
      parallelization_config:
        type: object
        default: {}
        description: "Configuration object for the selected parallelization strategy"

      # Logging arguments
      logging_config:
        type: string
        enum: ["none", "wandb"]
        default: "none"
        description: "Which logging strategy to use"

      # Seed arguments
      seed:
        type: [integer, 'null']
        default: null
        description: "Seed for reproducibility"

    required:
      - dataset
      - model_name
      - precision
      - number_epochs
      - batch_size
      - gradient_accumulation_steps
      - grad_clip
      - lr
      - lr_decay
      - lr_scheduler
      - warmup_proportion
      - weight_decay
      - beta1
      - beta2
      - parallelization_strategy
      - output_dir

    dependentSchemas:
      fsdp:
        properties:
          parallelization_config:
            $ref: "strategy/fsdp.schema.yaml"
        required: ["parallelization_config"]
      ddp:
        properties:
          parallelization_config:
            $ref: "strategy/ddp.schema.yaml"
        required: ["parallelization_config"]
      deep_speed:
        properties:
          parallelization_config:
            $ref: "strategy/deepspeed.schema.yaml"
        required: ["parallelization_config"]
      wandb:
        properties:
          logging_config:
            $ref: "logging/training_logging.schema.yaml"
        required: ["logging_config"]