$schema: "http://json-schema.org/draft-07/schema#"
$id: "mlm_training.schema.yaml"
description: "Schema for Masked Language Model training configuration"

allOf:
  - $ref: "file:///workspace/config/schemas/base.schema.yaml"
  - $ref: "file:///workspace/config/schemas/training/components/model.schema.yaml"
  - $ref: "file:///workspace/config/schemas/training/components/data.schema.yaml"
  - $ref: "file:///workspace/config/schemas/training/components/training_args.schema.yaml"
  - $ref: "file:///workspace/config/schemas/training/components/optimizer.schema.yaml"
  - $ref: "file:///workspace/config/schemas/training/components/scheduler.schema.yaml"
  - type: object
    properties:
      # MLM-specific model default
      model_name:
        type: string
        default: "bert-base-uncased"
        description: "Name or path of the masked language model to load"

      # MLM-specific arguments
      mlm_probability:
        type: number
        default: 0.15
        minimum: 0.0
        maximum: 1.0
        description: "Probability of masking tokens during MLM training"
      
      ignore_index:
        type: integer
        default: -100
        description: "Token ID to ignore in loss calculation"

      # Training strategy arguments
      parallelization_strategy:
        type: string
        enum: ["none", "ddp", "fsdp", "deep_speed", "dp"]
        default: "none"
        description: "Which distributed training strategy to use"

      # Parallelization config - details differ depending on strategy
      parallelization_config:
        type: object
        default: {}
        description: "Configuration object for the selected parallelization strategy"

      # Logging arguments
      logging_config:
        type: string
        enum: ["none", "wandb"]
        default: "none"
        description: "Which logging strategy to use"

      # Seed arguments
      seed:
        type: [integer, 'null']
        default: null
        description: "Seed for reproducibility"

    required:
      - dataset
      - model_name
      - precision
      - number_epochs
      - batch_size
      - gradient_accumulation_steps
      - grad_clip
      - lr
      - lr_decay
      - lr_scheduler
      - warmup_proportion
      - weight_decay
      - beta1
      - beta2
      - parallelization_strategy
      - output_dir

    dependentSchemas:
      fsdp:
        properties:
          parallelization_config:
            $ref: "strategy/fsdp.schema.yaml"
        required: ["parallelization_config"]
      ddp:
        properties:
          parallelization_config:
            $ref: "strategy/ddp.schema.yaml"
        required: ["parallelization_config"]
      deep_speed:
        properties:
          parallelization_config:
            $ref: "strategy/deepspeed.schema.yaml"
        required: ["parallelization_config"]
      wandb:
        properties:
          logging_config:
            $ref: "logging/training_logging.schema.yaml"
        required: ["logging_config"]