name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install PyTorch CPU version first to avoid build issues
        pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        pip install -r requirements.txt
    
    - name: Ensure test fixtures directories exist
      run: |
        mkdir -p tests/fixtures/data/sample_text
        mkdir -p tests/fixtures/data/tokenized_dataset
    
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest (CPU only tests)
      run: |
        # Set CI environment variable to allow tests to detect they're running in CI
        export CI=true
        pytest -v -m "not requires_gpu" tests/
    
    - name: Check test coverage
      run: |
        pytest --cov=src --cov-report=term-missing -m "not requires_gpu" tests/