name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: make build
    
    - name: Run unit tests in Docker
      run: |
        # Run CPU-only unit tests in Docker container
        docker run --rm $(docker build -q .) pytest -v -m "not requires_gpu" tests/unit

    - name: Run integration tests in Docker
      run: |
        # Run CPU-only integration tests in Docker container
        docker run --rm $(docker build -q .) pytest -v -m "not requires_gpu" tests/integration

    - name: Run coverage report in Docker
      run: |
        # Run coverage report in Docker container
        docker run --rm $(docker build -q .) pytest --cov=src --cov-report=term-missing -m "not requires_gpu" tests/